app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function () {
     Route::auth();
     Route::get('/home', 'HomeController@index');
     Route::get('/', function () {
    	return view('welcome');
	});

});





// Route::get('/login', 'Auth\AuthController@showLoginForm');
// Route::post('/login', 'Auth\AuthController@login');
// Route::get('/logout', 'Auth\AuthController@logout');





Route::get('/admin/login', function(){
	return view('login.adminLogin');
});

Route::post('/admin/login', 'AdminController@login');
Route::get('/admin/logout',  'AdminController@logout');

// resouce for company
Route::group(['middleware' => 'auth.super_admin_or_company_admin'], function()
{
    Route::resource('users', 'UserController');
});


Route::group(['middleware' => 'auth'], function()
{
	
    Route::resource('counters', 'CounterController');
    Route::resource('buses', 'BusController');
    Route::resource('seats', 'SeatController');
    Route::resource('routes', 'RouteController');
    Route::resource('coaches', 'CoachController');
    Route::resource('route_zones', 'RouteZoneController');
    Route::resource('seat_arrangements' , 'SeatArrangementController');
    Route::resource('coach_departure_times', 'CoachDepartureTimeController');
   
});
Route::group(['middleware' => 'auth.super_admin'], function()
{
	Route::resource('zones', 'ZoneController');
	Route::resource('companies', 'CompanyController');
    Route::resource('seat_types', 'SeatTypeController');
    Route::resource('coach_types', 'CoachTypeController');
	
});

app/SeatArrangement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SeatArrangement extends Model
{
    
    protected $fillable = [
    	'seat_id', 'row_id', 'col_id', 'seat_type_id', 'seat_name', 'modified_by', 'modification_date',
    ];
    public function seat()
    {
    	return $this->belongsTo('App\Seat');
    }
    public function seat_type()
    {
    	return $this->belongsTo('App\SeatType');
    }
}

app/Http/Controllers/SeatArrangementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


use App\Http\Requests;
use App\Admin;
use App\Bus;
use App\Coach;
use App\CoachDepartureTime;
use App\CoachType;
use App\Company;
use App\Counter;
use App\Fare;
use App\CoachZone;
use App\Seat;
use App\SeatArrangement;
use App\SeatType;
use App\User;
use App\Route;
use App\Zone;

use Carbon\Carbon;

class SeatArrangementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $seat_arrangements = SeatArrangement::paginate(20);
        $serial = 1;

        return view('seat_arrangement.index', compact('seat_arrangements', 'serial'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $seats = Seat::all();
        $seat_types = SeatType::all();
        return view('seat_arrangement.create',compact('seats', 'seat_types'));        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        for($i = 0 ; $i < count($request->row) ; $i++)
        {
            $seat_arrangement = new SeatArrangement;
            $seat_arrangement->seat_id = $request->seat_id;
            $seat_arrangement->row_id = $request->row[$i];
            $seat_arrangement->col_id = $request->col[$i];
            $seat_arrangement->seat_type_id = $request->seat_type[$i];
            $seat_arrangement->seat_name = $request->name[$i];
            $seat_arrangement->modified_by = \Auth::user()->id;
            $seat_arrangement->modification_date = Carbon::now();

            $seat_arrangement->save();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/seat_arrangement/create.blade.php
@extends('layouts.index')

@section('content')

<div class="col-lg-12 col-sm-12">
    <div class="row">
        <div id="seat" class="col-md-6">
                      
            
        </div>
        <div id="seat_and_seat_type" class="col-md-6">

            <label for="input_seat">Seat </label>
            <select name="seat_id" class="form-control" id="seat_arrange_id" >
                @foreach( $seats as $seat)
                {

                <option value={{$seat->id}} > {{$seat->seat_name}}  </option> 
                }
                @endforeach
            </select>
            

        </div>
        <div class="col-md-6">
            
            <form>
                {{ csrf_field() }}
            
            <table>
                <tr>
                    <td>Seat Position</td>
                    <td><input type="text" id="seat_position" value="" readonly/></td>
                </tr>
                
                <tr>
                    <td>Row</td>
                    <td><input type="text" id="row"/></td>
                </tr>
                <tr>
                    <td>Column</td>
                    <td><input type="text" id="column"/></td>
                </tr>
                <tr>
                    <td>Seat Name</td>
                    <td><input type="text" id="name"/></td>
                </tr>
                <tr>
                    <td>Seat Type</td>
                    <td>
                        <select id="seat-type">
                            @foreach( $seat_types as $seat_type)
                            {

                            <option value={{$seat_type->id}} selected="selected" > {{$seat_type->seat_type_name}}  </option> 
                            }
                            @endforeach 
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"><button id="submit_form">Update Seat</button></td>
                </tr>
            </table>
        </form>
        </div>
        <div class="col-md-6">
            <button id="save_seat" class="btn btn-primary">Save Seat</button>
        </div>
        

    </div>
</div>


<script src={{asset('js/company_admin/buslayout.js')}}></script>

@endsection

resources/views/seat_arrangement/edit.blade.php
 @extends('layouts.index')

 @section('content')
 <div class="panel panel-default">
     <div class="panel-heading">Please Input New Counters</div>
     <div class="panel-body">
         <div class="col-sm-4">
             <form action="/coaches/{{$coach->
                 id}}" method="POST" >
                    {{ csrf_field() }}
                 <input type="hidden" name="_method" value="PUT" /> 

                 <label for="input_coach_name">Coach Name</label>
                 <input type="text" name="coach_name" id="input_coach_name" class="form-control" value="{{$coach->coach_name}}"> 

                 <label for="input_route">Route</label>
                 <select name="coach_type_id" class="form-control" >
                     @foreach( $coach_types as $coach_type)
                        {
                        
                        @if($coach_type->id == $coach->coach_type_id)
                        <option value={{$coach_type->id}} selected="selected"> {{$coach_type->coach_type}}</option>
                        @else
                        <option value={{$coach_type->id}} > {{$coach_type->coach_type}}</option>
                        @endif 
                        }
                        @endforeach
                 </select>

                 <label for="input_route">Route</label>
                 <select name="route_id" class="form-control" >
                     @foreach( $routes as $route)
                    {
                        @if($route->id == $coach->route_id)
                        <option value={{$route->id}} selected="selected"> {{$route->route_name}}</option>
                        @else
                        <option value={{$route->id}} > {{$route->route_name}}</option>
                        @endif
                     }
                    @endforeach
                 </select>

                 <label for="input_seat">Seat</label>
                 <select name="seat_id" class="form-control">
                     @foreach( $seats as $seat)
                    {
                     
                     @if($seat->id == $coach->seat_id)
                     <option value={{$seat->id}} selected="selected"> {{$seat->seat_name}}</option>
                     @else
                     <option value={{$seat->id}} > {{$seat->seat_name}}</option>
                     @endif
                     }
                    @endforeach
                 </select>

                 <label for="input_company">Starting Counter</label>
                 <select name="starting_counter_id" class="form-control">
                     @foreach( $counters as $counter)
                    {
                     
                     @if($counter->id == $coach->starting_counter_id)
                     <option value={{$counter->id}} selected="selected" > {{$counter->counter_name}}</option>
                     @else
                     <option value={{$counter->id}} > {{$counter->counter_name}}</option>
                     @endif

                     }
                    @endforeach
                 </select>

                 <label for="input_starting_time">Starting Time</label>
                 <input type="time" name="starting_time" id="input_starting_time" class="form-control" value={{$coach->starting_time}}> 

                 <label for="input_company">Ending Counter</label>
                 <select name="ending_counter_id" class="form-control">
                     @foreach( $counters as $counter)
                    {
                     
                     
                     @if($counter->id == $coach->ending_counter_id)
                     <option value={{$counter->id}} selected="selected" > {{$counter->counter_name}}</option>
                     @else
                     <option value={{$counter->id}} > {{$counter->counter_name}}</option>
                     @endif

                     }
                    @endforeach
                 </select>

                 <label for="input_ending_time">Ending Time</label>
                 <input type="text" name="ending_time" id="input_ending_time" class="form-control" value={{$coach->ending_time}}> 
                    <button type="submit" class = "btn btn-default"> <i class="fa fa-btn fa-plus"></i>
                    Update
                    </button>

         </form>

     </div>
 </div>

 </div>
 @endsection

resources/views/seat_arrangement/index.blade.php
@extends('layouts.index')

@section('content')
        <div class="container narrow">
            <div>
                <div class="panel panel-default">
                <div class="panel-heading">
                    Edit and Delete seat_arrangement
                </div>
                <div class="panel-body">
                    <table class="table table-striped place-table">
                        <thead>
                        <th>Serial</th>
                        <th>Seat</th>
                        <th>Row</th>
                        <th>Column</th>
                        <th>Seat Type</th>
                        <th>Seat Name</th>
                        <th>Modified By</th>
                        <th>Modification Date</th>

                        </thead>


                        <tbody id='seat_arrangement-list' name = 'seat_arrangement-list' >
                        @foreach($seat_arrangements as $seat_arrangement)
                            <tr id='seat_arrangement{{$seat_arrangement->id}}'>

                                <td class="table-text">{{$serial++}}</td>
                                <td class="table-text">{{\App\Seat::find($seat_arrangement->seat_id)->seat_name}}</td>
                                <td class="table-text">{{$seat_arrangement->row_id}}</td>
                                <td class="table-text">{{$seat_arrangement->col_id}}</td>
                                <td class="table-text">{{\App\SeatType::find($seat_arrangement->seat_type_id)->seat_type_name}}</td>
                                <td class="table-text">{{$seat_arrangement->seat_name}}</td>
                                
                                <td class="table-text">{{\App\User::findOrFail($seat_arrangement->modified_by)->fullname}}</td>
                                
                                <td class="table-text">{{$seat_arrangement->modification_date}}</td>
                                

                        
                                 <td>
                                    <a href="{{ route('seat_arrangements.edit', $seat_arrangement->id) }}" class="btn btn-primary">Edit </a>
                                </td>


                                <td>
                                    <form action="/seat_arrangements/{{ $seat_arrangement->id }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}

                                        <button type="submit" id="delete-seat_arrangement-{{ $seat_arrangement->id }}" class="btn btn-danger">
                                            <i class="fa fa-btn fa-trash"></i>Delete
                                        </button>
                                    </form>
                                </td>
 
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
            </div>
        </div>
        </div>
        </div>
            
        
        <div class="pagination">
                {!! $seat_arrangements->links() !!}        
        </div>

@endsection