app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function () {
     Route::auth();
     Route::get('/home', 'HomeController@index');
     Route::get('/', function () {
    	return view('welcome');
	});

});





// Route::get('/login', 'Auth\AuthController@showLoginForm');
// Route::post('/login', 'Auth\AuthController@login');
// Route::get('/logout', 'Auth\AuthController@logout');





Route::get('/admin/login', function(){
	return view('login.adminLogin');
});

Route::post('/admin/login', 'AdminController@login');
Route::get('/admin/logout',  'AdminController@logout');

// resouce for company
Route::group(['middleware' => 'auth.super_admin_or_company_admin'], function()
{
    Route::resource('users', 'UserController');
});


Route::group(['middleware' => 'auth'], function()
{
	
    Route::resource('counters', 'CounterController');
    Route::resource('buses', 'BusController');
    Route::resource('seats', 'SeatController');
    Route::resource('routes', 'RouteController');
    Route::resource('coaches', 'CoachController');
    Route::resource('route_zones', 'RouteZoneController');
    Route::resource('seat_arrangements' , 'SeatArrangementController');
    Route::resource('coach_departure_times', 'CoachDepartureTimeController');
   
});
Route::group(['middleware' => 'auth.super_admin'], function()
{
	Route::resource('zones', 'ZoneController');
	Route::resource('companies', 'CompanyController');
    Route::resource('seat_types', 'SeatTypeController');
    Route::resource('coach_types', 'CoachTypeController');
	
});

app/Http/Controllers/SeatTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Http\Requests;
use App\SeatType;

class SeatTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $seat_types = SeatType::paginate(15);
        $serial = 1;
        return view('seat_type.index', compact('seat_types', 'serial'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('seat_type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //$seat_type = new SeatType;
        
        //$seat_type->seat_type_name = $request->seat_type_name;
        //$seat_type = $request->all();
        
        //$seat_type->modified_by = \Auth::user()->id;
        //$seat_type->modification_date = Carbon::now();

        $request['modified_by'] = \Auth::user()->id;
        $request['modification_date'] = Carbon::now();

        //$seat_type = $request->all();
        $seat_type = SeatType::create($request->all());

        //$seat_type->save();

        return view('seat_type.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $seat_type = SeatType::findorfail($id);
        
        return view('seat_type.edit', compact('seat_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $seat_type = SeatType::findOrFail($id);
        $seat_type->seat_type_name = $request->seat_type_name;
        $seat_type->modified_by = \Auth::user()->id;
        $seat_type->modification_date = Carbon::now();
        $seat_type->save();

        return redirect('/seat_types/');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        $seat_type = SeatType::destroy($id);

        return redirect('/seat_types/');
    }
}

resources/views/seat_type/create.blade.php
@extends('layouts.index')

@section('content')

<div class="container narrow">
 <div>
  <div class="panel panel-default">
    <div class="panel-heading">
      Please Input New Seat Type
    </div>
    <div class="panel-body">
      <div class="col-sm-4">
        <form action="/seat_types/" method="post" >
          {{ csrf_field() }}
          

          <label for="input_seat_type">Seat type</label>
          <input type="text" name="seat_type_name" id="input_seat_type" class="form-control">

          <button type="submit" class = "btn btn-default">
            <i class="fa fa-btn fa-plus"></i>Add
          </button>

        </form> 
      </div>
    </div>   
    
  </div>
</div>
</div>




@endsection

resources/views/seat_type/edit.blade.php
@extends('layouts.index')

@section('content')

<div class="container narrow">
 <div>
    <div class="panel panel-default">
        <div class="panel-heading">
            Please Input New Seat Type
        </div>
        <div class="panel-body">
            <div class="col-sm-4">
                <form action="/seat_types/{{$seat_type->id}}" method="post" >
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT" />

                    <label for="input_seat_type">Seat type</label>
                    <input type="text" name="seat_type_name" id="input_seat_type" class="form-control" value={{$seat_type->seat_type_name}}>

                    <button type="submit" class = "btn btn-default">
                        <i class="fa fa-btn fa-plus"></i>Add
                    </button>

                </form>
            </div> 
        </div>   
        
    </div>
</div>
</div>




@endsection

resources/views/seat_type/index.blade.php
@extends('layouts.index')

@section('content')
        <div class="container narrow">
            <div>
                <div class="panel panel-default">
                <div class="panel-heading">
                    Edit and Delete Company
                </div>
                <div class="panel-body">
                    <table class="table table-striped place-table">
                        <thead>
                        <th>Serial</th>
                        <th>Seat Type</th>
                        <th>Modified By</th>
                        <th>Modification Date</th>
                        <th>Action</th>

                        </thead>


                        <tbody id='seat_type-list' name = 'seat_type-list' >
                        @foreach($seat_types as $seat_type)
                            <tr id='seat_type{{$seat_type->id}}'>

                                <td class="table-text">{{$serial++}}</td>
                                <td class="table-text">{{$seat_type->seat_type_name}}</td>
                                <td class="table-text">{{\App\User::findOrFail($seat_type->modified_by)->fullname}}</td>
                                <td class="table-text">{{$seat_type->modification_date}}</td>
                                
                        
                                 <td>
                                    <a href="{{ route('seat_types.edit', $seat_type->id) }}" class="btn btn-primary">Edit</a>
                                </td>


                                <td>
                                    <form action="/seat_types/{{ $seat_type->id }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}

                                        <button type="submit" id="delete-seat-type-{{ $seat_type->id }}" class="btn btn-danger">
                                            <i class="fa fa-btn fa-trash"></i>Delete
                                        </button>
                                    </form>
                                </td>
 
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
            </div>
        </div>
        </div>
        </div>
            
        
        <div class="pagination">
                {!! $seat_types->links() !!}        
        </div>

@endsection