app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function () {
     Route::auth();
     Route::get('/home', 'HomeController@index');
     Route::get('/', function () {
    	return view('welcome');
	});

});





// Route::get('/login', 'Auth\AuthController@showLoginForm');
// Route::post('/login', 'Auth\AuthController@login');
// Route::get('/logout', 'Auth\AuthController@logout');





Route::get('/admin/login', function(){
	return view('login.adminLogin');
});

Route::post('/admin/login', 'AdminController@login');
Route::get('/admin/logout',  'AdminController@logout');

// resouce for company
Route::group(['middleware' => 'auth.super_admin_or_company_admin'], function()
{
    Route::resource('users', 'UserController');
});


Route::group(['middleware' => 'auth'], function()
{
	
    Route::resource('counters', 'CounterController');
    Route::resource('buses', 'BusController');
    Route::resource('seats', 'SeatController');
    Route::resource('routes', 'RouteController');
    Route::resource('coaches', 'CoachController');
    Route::resource('route_zones', 'RouteZoneController');
    Route::resource('seat_arrangements' , 'SeatArrangementController');
    Route::resource('coach_departure_times', 'CoachDepartureTimeController');
   
});
Route::group(['middleware' => 'auth.super_admin'], function()
{
	Route::resource('zones', 'ZoneController');
	Route::resource('companies', 'CompanyController');
    Route::resource('seat_types', 'SeatTypeController');
    Route::resource('coach_types', 'CoachTypeController');
	
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
         'company_name','id','modified_by', 'modification_date',
    ];
    protected $hidden = [
        
    ];
    public function buses()
    {

    	return $this->hasMany('App\Bus');
    }

    public function routes()
    {
    	return $this->hasMany('App\Route');
    }

    public function users()
    {
    	return $this->hasMany('App\User');
    }

    public function counters()
    {
    	return $this->hasMany('App\Counter');
    }

    public function seats()
    {
    	return $this->hasMany('App\Seat');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use Carbon\Carbon;

use App\Http\Requests;

class CompanyController extends Controller
{
	
	public function index()
	{
		    
			$companies = Company::Paginate(15);
			$serial = 1;
			
    		return view('company.index', compact('companies', 'serial'));
	}

	public function edit($id)
	{
		$company = Company::findorfail($id);
		
		return view('company.edit', compact('company'));

	}

	public function create()
	{

		return view('company.create');
	}
	


	public function show($company_id)
	{
		$company = Company::find($company_id);

    	return \Response::json($company);
	}


	public function store(Request $request)
	{
		$company = new Company;
		
		$company->company_name = $request->company_name;
		
		$company->modified_by = \Auth::guard('admins')->user()->id;
		$company->modification_date = Carbon::now()->toDateString();
		$company->save();

    	return view('company.create');
	}


	public function update(Request $request, $company_id)
	{
		$company = Company::find($company_id);

	    $company->company_name = $request->company_name;
	    $company->modified_by = \Auth::guard('admins')->user()->id;

		$company->modification_date = Carbon::now()->toDateString();
	    

	    $company->save();

	    return redirect('/companies/');
	}

    public function destroy($company_id)
    {
    	$company = Company::destroy($company_id);

    	return redirect('/companies/');
    }
}

resources/views/company/create.blade.php
@extends('layouts.index')

@section('content')
    
       <div class="container narrow">
           <div>
                <div class="panel panel-default">
                <div class="panel-heading">
                    Please Input New Routes
                </div>
                <div class="panel-body">
                            <div class="col-sm-4">
                                <form action="/companies/" method="post" >
                                {{ csrf_field() }}
                                

                                <label for="input_company">Company Name</label>
                                <input type="text" name="company_name" id="input_company" class="form-control">

                                


                                <button type="submit" class = "btn btn-default">
                                    <i class="fa fa-btn fa-plus"></i>Add
                                </button>

                            </form> 
                            </div>
                    </div>   
                            
                </div>
                </div>
        </div>
   

@endsection

resources/views/company/edit.blade.php
 @extends('layouts.index')

@section('content')

        <div class="container narrow">
        <div>

        <div class="panel panel-default">
                <div class="panel-heading">
                    Please Input New Company
                </div>
                <div class="panel-body">
                            <div class="col-sm-4">
                                <form action="/companies/{{$company->id}}" method="POST" >
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="PUT" />

                                <label for="input_company">Company Name</label>
                                <input type="text" name="company_name" id="input_company" class="form-control" value={{$company->company_name}}>

                                



                                <button type="submit" class = "btn btn-default">
                                    <i class="fa fa-btn fa-plus"></i>Update
                                </button>

                            </form> 
                            </div>
                    </div>   
                            
                </div>
                </div>
        </div>
            
@endsection

resources/views/company/index.blade.php
@extends('layouts.index')

@section('content')
        <div class="container narrow">
            <div>
                <div class="panel panel-default">
                <div class="panel-heading">
                    Edit and Delete Company
                </div>
                <div class="panel-body">
                    <table class="table table-striped place-table">
                        <thead>
                        <th>Serial</th>
                        <th>Company Name</th>
                        <th>Modified By</th>
                        <th>Modification Date</th>
                        <th>Action</th>

                        </thead>


                        <tbody id='company-list' name = 'company-list' >
                        @foreach($companies as $company)
                            <tr id='company{{$company->id}}'>

                                <td class="table-text">{{$serial++}}</td>
                                <td class="table-text">{{$company->company_name}}</td>
                                <td class="table-text">{{$company->modified_by}}</td>
                                <td class="table-text">{{$company->modification_date}}</td>
                                
                        
                                 <td>
                                    <a href="{{ route('companies.edit', $company->id) }}" class="btn btn-primary">Edit company</a>
                                </td>


                                <td>
                                    <form action="/companies/{{ $company->id }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}

                                        <button type="submit" id="delete-route-{{ $company->id }}" class="btn btn-danger">
                                            <i class="fa fa-btn fa-trash"></i>Delete
                                        </button>
                                    </form>
                                </td>
 
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
            </div>
        </div>
        </div>
        </div>
            
        
        <div class="pagination">
                {!! $companies->links() !!}        
        </div>

@endsection