app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function () {
     Route::auth();
     Route::get('/home', 'HomeController@index');
     Route::get('/', function () {
    	return view('welcome');
	});

});





// Route::get('/login', 'Auth\AuthController@showLoginForm');
// Route::post('/login', 'Auth\AuthController@login');
// Route::get('/logout', 'Auth\AuthController@logout');





Route::get('/admin/login', function(){
	return view('login.adminLogin');
});

Route::post('/admin/login', 'AdminController@login');
Route::get('/admin/logout',  'AdminController@logout');

// resouce for company
Route::group(['middleware' => 'auth.super_admin_or_company_admin'], function()
{
    Route::resource('users', 'UserController');
});


Route::group(['middleware' => 'auth'], function()
{
	
    Route::resource('counters', 'CounterController');
    Route::resource('buses', 'BusController');
    Route::resource('seats', 'SeatController');
    Route::resource('routes', 'RouteController');
    Route::resource('coaches', 'CoachController');
    Route::resource('route_zones', 'RouteZoneController');
    Route::resource('seat_arrangements' , 'SeatArrangementController');
    Route::resource('coach_departure_times', 'CoachDepartureTimeController');
   
});
Route::group(['middleware' => 'auth.super_admin'], function()
{
	Route::resource('zones', 'ZoneController');
	Route::resource('companies', 'CompanyController');
    Route::resource('seat_types', 'SeatTypeController');
    Route::resource('coach_types', 'CoachTypeController');
	
});

app/Bus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bus extends Model
{
    protected $fillable = [
    	'bus_number', 'seats', 'company_id', 'modified_by', 'modification_date',
    ];
    public function company()
    {

    	return $this->belongsTo('App\Company');
    }
}

app/Http/Controllers/BusController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Bus;
use Carbon\Carbon;

class BusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $buses = Bus::paginate(60);
        $serial = 1;

        return view('bus.index', compact('buses', 'serial'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bus.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $bus = new Bus;
        
        $bus->bus_number = $request->bus_number;
        $bus->seats = $request->seats;

        //$bus = $request->all();
        
        $bus->modified_by = \Auth::user()->id;
        $bus->company_id = \Auth::user()->company_id;
        $bus->modification_date = Carbon::today();
        $bus->save();

        return view('bus.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bus = Bus::find($id);

        return view('bus.edit', compact('bus'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $bus = Bus::find($id);
        
        // $bus->bus_number = $request->bus_number;
        //$bus = $request->all();
        $bus->bus_number = $request->bus_number;
        $bus->seats = $request->seats;
        $bus->modified_by = \Auth::user()->id;
        $bus->modification_date = Carbon::today();
        $bus->save();

        return redirect('/buses/');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $bus = Bus::destroy($id);
        return redirect()->back();
    }
}

resources/views/bus/create.blade.php
@extends('layouts.index')

@section('content')

<div class="container narrow">
 <div>
    <div class="panel panel-default">
        <div class="panel-heading">
            Please Input New Buses
        </div>
        <div class="panel-body">
            <div class="col-sm-4">
                <form action="/buses/" method="post" >
                    {{ csrf_field() }}
                    

                    <label for="input_bus_number">Bus Number</label>
                    <input type="text" name="bus_number" id="input_bus_number" class="form-control">
                    <label for="input_seats">Seats</label>
                    <input type="text" name="seats" id="input_seats" class="form-control">
                    


                    <button type="submit" class = "btn btn-default">
                        <i class="fa fa-btn fa-plus"></i>Add
                    </button>

                </form> 
            </div>
        </div>   
        
    </div>
</div>
</div>



@endsection

resources/views/bus/edit.blade.php
@extends('layouts.index')

@section('content')

<div class="container narrow">
 <div>
    <div class="panel panel-default">
        <div class="panel-heading">
            Please Input New Buses
        </div>
        <div class="panel-body">
            <div class="col-sm-4">
                <form action="/buses/{{$bus->id}}" method="post" >
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT" />

                    <label for="input_bus_number">Bus Number</label>
                    <input type="text" name="bus_number" id="input_bus_number" class="form-control" value={{$bus->bus_number}}>
                    <label for="input_seats">Seats</label>
                    <input type="text" name="seats" id="input_seats" class="form-control" value={{$bus->seats}}>
                    


                    <button type="submit" class = "btn btn-default">
                        <i class="fa fa-btn fa-plus"></i>Update
                    </button>

                </form>
            </div> 
        </div>   
        
    </div>
</div>
</div>



@endsection

resources/views/bus/index.blade.php
@extends('layouts.index')

@section('content')
        <div class="container narrow">
            <div>
                <div class="panel panel-default">
                <div class="panel-heading">
                    Edit and Delete Bus
                </div>
                <div class="panel-body">
                    <table class="table table-striped place-table">
                        <thead>
                        <th>Serial</th>
                        <th>Bus Number</th>
                        <th>Seats</th>
                        <th>Modified By</th>
                        <th>Modification Date</th>
                        <th>Action</th>

                        </thead>


                        <tbody id='bus-list' name = 'bus-list' >
                        @foreach($buses as $bus)
                            <tr id='bus{{$bus->id}}'>

                                <td class="table-text">{{$serial++}}</td>
                                <td class="table-text">{{$bus->bus_number}}</td>
                                <td class="table-text">{{$bus->seats}}</td>
                                <td class="table-text">{{\App\User::find($bus->modified_by)->fullname}}</td>
                                <td class="table-text">{{$bus->modification_date}}</td>
                                
                        
                                 <td>
                                    <a href="{{ route('buses.edit', $bus->id) }}" class="btn btn-primary">Edit</a>
                                </td>


                                <td>
                                    <form action="/buses/{{ $bus->id }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}

                                        <button type="submit" id="delete-bus-{{ $bus->id }}" class="btn btn-danger">
                                            <i class="fa fa-btn fa-trash"></i>Delete
                                        </button>
                                    </form>
                                </td>
 
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
            </div>
        </div>
        </div>
        </div>
         
        
        <div class="pagination">
                {!! $buses->links() !!}        
        </div>

@endsection